[build]
  functions = "users"

[[redirects]]
  from = "/api/create-user"
  to = "/.netlify/functions/create-user"
  status = 200
  
[[redirects]]
  from = "/api/get-user/*"
  to = "/.netlify/functions/get-user/:splat"
  status = 200
  
[[redirects]]
  from = "/api/save-profile/*"
  to = "/.netlify/functions/save-profile/:splat"
  status = 200